
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - mindebase_redis
      - mindebase_mysql
    environment:
      SPRING_REDIS_HOST: ${REDIS_HOST}
      SPRING_REDIS_PORT: ${REDIS_PORT}
      SPRING_DATASOURCE_URL: jdbc:mysql://${DATASOURCE_URL}:${DATABASE_PORT}/${DATABASE_NAME}
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: angular-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - app-network

  mindebase_redis:
    image: redis:7-alpine
    container_name: mindebase_redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  mindebase_mysql:
    image: mysql:8.0
    container_name: mindebase_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:

volumes:
  redis_data:
  mysql_data:
