CREATE TABLE ms_order_status (
    id TINYINT PRIMARY KEY,
    status_name VARCHAR(50) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO ms_order_status (id, status_name) VALUES 
(1, 'PENDING'),
(2, 'CONFIRMED'),
(3, 'COOKING'),
(4, 'DELIVERING'),
(5, 'COMPLETED'),
(6, 'CANCELLED');